//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BotStorageEntities : DbContext
    {
        public BotStorageEntities()
            : base("name=BotStorageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SMSNoticeSettings> SMSNoticeSettings { get; set; }
        public virtual DbSet<SMSUserDayStatistic> SMSUserDayStatistic { get; set; }
        public virtual DbSet<SMSSendingQueue> SMSSendingQueue { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
    }
}
