//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSSendingQueue
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<System.TimeSpan> TimeFirstSmsSent { get; set; }
        public Nullable<System.TimeSpan> TimeSecondSmsSent { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
